### ISSUE TITLE
Please, write how use your code?

### ISSUE THREAD

**Issue by nenser** [TheLazzziest/Megaplan#1]
Could you write simple instruction about using your code?

For example, how I can get project list?

```
require dirname(__FILE__) . 'MegaplanAPI.php';

$r=new MegaplanApi('https', 'mymegaplan.local','user'.'password');
$r->auth();

$params=[
    'Folder'=>'all',
    'executor'=>123456,
];

$ProjectList=$r->getProjectList($params);
print_r($ProjectList);
```
I didn't get anything :(
What am I doing wrong?

Thanks!

**Comment by TheLazzziest** [comment]
Hey, as far as I remember you do all the stuff right. Unfortunately, I haven't been supporting it for some time and I don't have plans to continue developing it. Also, Megaplan's api is a close one, if I am not mistaken. Therefore, its api can be different right now. That is why, my code can be out of date at some placess.
I suggest you to fork my project and check the api of Megaplan by yourself. However, it's up to you, of course. 
If there will appear some questions concerning it's api or the library code, write me and I will try to help.
